### PR TITLE
Update Delete Command: Error Handling Fix Issues #131 and #143

### PR DESCRIPTION
**Pull request by ritvi12**
### Description

Updated the delete command to have more specific messages for error handling.

Example: In case of negative numbers or zero
Screenshot 2024-11-04 at 1 07 34 PM

Example: In case of invalid index

Screenshot 2024-11-04 at 2 49 40 AM

Example: In case of invalid name
Screenshot 2024-11-04 at 2 49 51 AM

### CODE REVIEW

**Comment by Bonzzz3** [comment]
Hmm I think unsigned integer is more often used in cs field. Would it be better if it is phrased as "Index provided is not a positive integer."

**Comment by ritvi12** [comment]
Ok. Will make the changes

**Review by myrilla12 — APPROVED** [review]
LGTM

**Review by Bonzzz3 — APPROVED** [review]
LGTM

**Pull request merged**
